name: Grade Submission
# ─────────────────────────────────────────────────────────────────────────────
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs:
  feedback:
        uses: DataScience4Psych/actions/.github/workflows/classroom.yml@main
        secrets: inherit
